# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Description of what the lane does"
  lane : build_ipa do
    build_ios_app(
      workspace: WORKSPACE_NAME,
      scheme: SCHEME_NAME,
      output_directory: PATH_FOR_IPA,
      output_name: IPA_NAME,
      export_method: “app-store”,
      include_bitcode: false,
      clean: true)
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number
    build_app(scheme: "Example")
    upload_to_testflight
  end
  
  lane :release do
    capture_screenshots
    build_app
    upload_to_app_store 	# Upload the screenshots and the binary to iTunes
    slack 			# Let your team-mates know the new version is live
  end

end
